version: '3.7'

services:
  django_gunicorn:
    image: deveaselabs/django-gunicorn:latest
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: deveaselabs/nginx:latest
    build: ./nginx
    volumes:
      - static:/static
    ports: 
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:

networks:
  app-network: